- hosts: all
  gather_facts: yes
  become: false  # prevent sudo for facts

- name: Create a folder
  hosts: all
  become: yes  # if needed to write to protected paths like /opt
  tasks:
    - name: Create /opt/myapp directory
      file:
        path: /opt/myapp
        state: directory
        owner: root
        group: root
        mode: '0755'

#- name: Install a simple package
#  hosts: all
#  become: yes
#  tasks:
#    - name: Ensure htop is installed
#      apt:
#        name: htop
#        state: present
#      when: ansible_os_family == "Debian"