- name: Install a simple package
  hosts: all
  become: yes
  tasks:
    - name: Ensure htop is installed
      apt:
        name: htop
        state: present
      when: ansible_os_family == "Debian"